import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { inflateRawSync } from 'node:zlib';
const repoRoot=path.resolve(import.meta.dirname,'..'),artifactRoot=path.join(repoRoot,'artifacts'),evidenceRoot=path.join(repoRoot,'evidence');
const attachments={
  "输入数据包.zip": "4a8752b10b2b0d20c8d6336b8faca0f250c4931874978aebf13b3c44f6645ac6",
  "reference.zip": "296506a31cc0f0e44063b24e2bf85c40d8bf558b2a1ff95ab61e0ec4a1d20ad7",
  "关键标准答案.xlsx": "4b7c309011a1a00c9b7d7afd341d55d475411da9f022c95c0532e857d71d8c6d",
  "任务规格转化.xlsx": "327d9f8236652f6e2d71ba9f39602771a0715d1128ae3fd988e85d38d4623c95"
},taskHashes={
  "任务名称.txt": "f9b406f37feb469da62d7ac73cf32f5da4952e25df06ec9622d43b1c3902ab96",
  "任务概要.txt": "1fda5e54ab0b70de2c23f97081731f3a62d95fb5f51dac74b92d944af0fcce8d",
  "任务prompt.txt": "896f7b754f7c62cad4ab70daa07f09c9f2d22b11a5611b6f7a064e414cf509cf",
  "关键动作.txt": "1d24a0f293004f31b259b7a066a93a67246c2a1ea290ceec4576a6bc038b3eb4",
  "评分表.txt": "6140025793e4fee254397a7e37c873636eb37b465858843748670e380c766dfc",
  "环境依赖.txt": "ce1428a40443284b051e5fa865ae0b346c4d8d1b1fa0d48a5bc4b771f0074f45",
  "相关专业软件的关键步骤.txt": "1967784b182837ab7b72eec670ca865095119aca3a0c005bfc65993a8231b569"
},deliveryMembers=[
  "output/playwright.config.ts",
  "output/reports/accessibility_contract.csv",
  "output/reports/persistence_checks.csv",
  "output/reports/player_state_matrix.csv",
  "output/reports/shortcut_assertions.csv",
  "output/tests/video_player_controls.spec.ts"
];
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),shaFile=f=>sha(fs.readFileSync(f)),assert=(v,m)=>{if(!v)throw new Error(m);};
function parseZipBytes(data){const files=new Map();let offset=0;while(offset+46<=data.length){if(data.readUInt32LE(offset)!==0x02014b50){offset+=1;continue;}const method=data.readUInt16LE(offset+10),compressedSize=data.readUInt32LE(offset+20),uncompressedSize=data.readUInt32LE(offset+24),nameLength=data.readUInt16LE(offset+28),extraLength=data.readUInt16LE(offset+30),commentLength=data.readUInt16LE(offset+32),localOffset=data.readUInt32LE(offset+42),name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/');if(!name.endsWith('/')){const localNameLength=data.readUInt16LE(localOffset+26),localExtraLength=data.readUInt16LE(localOffset+28),start=localOffset+30+localNameLength+localExtraLength,compressed=data.subarray(start,start+compressedSize),body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===uncompressedSize,'ZIP extraction error');files.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return files;}
const parseZip=file=>parseZipBytes(fs.readFileSync(file));async function extract(file,destination){for(const[name,bytes]of parseZip(file)){const target=path.resolve(destination,name);assert(target.startsWith(path.resolve(destination)+path.sep),'unsafe ZIP path');await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function sheets(file){const xml=parseZip(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map(m=>m[1]);}
async function run(command,args,cwd,env={}){const started=Date.now();return await new Promise(resolve=>{let child;try{child=spawn(command,args,{cwd,env:{...process.env,...env},windowsHide:true});}catch(error){resolve({code:1,stdout:'',stderr:error.message,elapsed_ms:Date.now()-started});return;}let stdout='',stderr='',settled=false;child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.on('error',e=>{if(!settled){settled=true;resolve({code:1,stdout,stderr:stderr+e.message,elapsed_ms:Date.now()-started});}});child.on('exit',code=>{if(!settled){settled=true;resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});}});});}
async function npmRun(args,cwd){const npmCli=process.env.npm_execpath;assert(npmCli,'npm CLI missing');return await run(process.execPath,[npmCli,...args],cwd);}
function treeDigest(root,ignored=new Set()){const lines=[];function visit(current,prefix=''){for(const e of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name))){const rel=prefix?prefix+'/'+e.name:e.name;if(ignored.has(rel.split('/')[0]))continue;const full=path.join(current,e.name);if(e.isDirectory())visit(full,rel);else lines.push(rel+'\0'+shaFile(full));}}visit(root);return sha(Buffer.from(lines.join('\n')));}
function normalize(name,bytes){const text=bytes.toString('utf8').replaceAll('\r\n','\n').trimEnd();if(name.endsWith('.csv')){const[head,...rows]=text.split('\n');return head+'\n'+rows.toSorted().join('\n');}return text;}
function compare(outputRoot,standard){const actual=[];function visit(current,prefix='output'){for(const e of fs.readdirSync(current,{withFileTypes:true})){const rel=prefix+'/'+e.name,full=path.join(current,e.name);if(e.isDirectory())visit(full,rel);else actual.push(rel.replaceAll('\\','/'));}}visit(outputRoot);actual.sort();assert(JSON.stringify(actual)===JSON.stringify(deliveryMembers),'delivery members differ');const h=crypto.createHash('sha256');for(const member of deliveryMembers){const a=normalize(member,fs.readFileSync(path.join(outputRoot,member.slice(7)))),e=normalize(member,standard.get(member));assert(a===e,'delivery differs '+member);h.update(a);}return h.digest('hex');}
async function prepare(label,mutate){const runRoot=path.join(os.tmpdir(),label);await fsp.rm(runRoot,{recursive:true,force:true});await fsp.mkdir(runRoot,{recursive:true});await extract(path.join(artifactRoot,'输入数据包.zip'),runRoot);const inputRoot=path.join(runRoot,'input_data'),standard=parseZip(path.join(artifactRoot,'reference.zip'));await fsp.writeFile(path.join(inputRoot,'starter','playwright.config.ts'),standard.get('output/playwright.config.ts'));await fsp.writeFile(path.join(inputRoot,'starter','tests','video_player_controls.spec.ts'),standard.get('output/tests/video_player_controls.spec.ts'));if(mutate)await mutate(inputRoot);return{inputRoot,outputRoot:path.join(runRoot,'output'),standard};}
async function install(inputRoot){let r=await npmRun(['ci'],inputRoot);assert(r.code===0,'npm ci failed '+r.stderr);r=await npmRun(['exec','--','playwright','install','chromium'],inputRoot);assert(r.code===0,'Chromium install failed '+r.stderr);return true;}
async function execute(inputRoot){return await npmRun(['run','process'],inputRoot);}
await fsp.rm(evidenceRoot,{recursive:true,force:true});await fsp.mkdir(evidenceRoot,{recursive:true});assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','Windows hosted runner required');for(const[name,expected]of Object.entries(attachments))assert(shaFile(path.join(artifactRoot,name))===expected,name+' checksum mismatch');for(const[name,expected]of Object.entries(taskHashes))assert(shaFile(path.join(repoRoot,'task',name))===expected,name+' task checksum mismatch');
const input=parseZip(path.join(artifactRoot,'输入数据包.zip')),standard=parseZip(path.join(artifactRoot,'reference.zip'));assert(JSON.stringify([...standard.keys()].sort())===JSON.stringify(deliveryMembers),'delivery member list mismatch');const platform=[...input,...standard].filter(([name,bytes])=>(bytes[0]===0x7f&&bytes.subarray(1,4).toString()==='ELF')||/\.(?:sh|bash|so)$/iu.test(name));assert(platform.length===0,'platform member found');assert(JSON.stringify(sheets(path.join(artifactRoot,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'answer sheets mismatch');assert(JSON.stringify(sheets(path.join(artifactRoot,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'spec sheets mismatch');
const cleanRuns=[];for(const label of ['Q10436 clean course player','Q10436 中文 空格 播放器']){const p=await prepare(label),before=treeDigest(p.inputRoot,new Set(['node_modules','output']));await install(p.inputRoot);const r=await execute(p.inputRoot);assert(r.code===0,'browser run failed '+r.stdout+' '+r.stderr);const after=treeDigest(p.inputRoot,new Set(['node_modules','output']));assert(before===after,'business input changed');const digest=compare(p.outputRoot,p.standard);cleanRuns.push({directory_label:label,exit_code:r.code,input_digest_before:before,input_digest_after:after,semantic_digest:digest,elapsed_ms:r.elapsed_ms});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'clean results differ');
const mutation=await prepare('Q10436 caption change',async inputRoot=>{const tracksFile=path.join(inputRoot,'fixtures','caption_tracks.json'),casesFile=path.join(inputRoot,'fixtures','player_cases.json'),tracks=JSON.parse(await fsp.readFile(tracksFile,'utf8')),cases=JSON.parse(await fsp.readFile(casesFile,'utf8')),changed='新しい配送案内を確認してください';tracks.find(item=>item.lang==='ja').shipping=changed;cases.find(item=>item.kind==='caption_persistence').expected_caption_text=changed;await fsp.writeFile(tracksFile,JSON.stringify(tracks,null,2)+'\n');await fsp.writeFile(casesFile,JSON.stringify(cases,null,2)+'\n');});await install(mutation.inputRoot);let r=await execute(mutation.inputRoot);assert(r.code===0,'positive mutation failed '+r.stderr);const changed=await fsp.readFile(path.join(mutation.outputRoot,'reports','player_state_matrix.csv'),'utf8');assert(changed.includes('新しい配送案内を確認してください'),'caption change not reflected');assert(!changed.includes('配送予定日を確認してください'),'old caption remained in changed report');
const invalid=await prepare('Q10436 invalid input',async inputRoot=>{await fsp.rename(path.join(inputRoot,'fixtures','caption_tracks.json'),path.join(inputRoot,'fixtures','caption_tracks.json.missing'));});await install(invalid.inputRoot);r=await execute(invalid.inputRoot);assert(r.code!==0,'missing subtitle fixture accepted');assert(!fs.existsSync(invalid.outputRoot),'invalid input left delivery output');
const evidence={schema_version:1,task_asset_id:'playwright_course_video_caption_keyboard',result:'PASS',generated_at_utc:new Date().toISOString(),git_commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,runner:{os:process.env.RUNNER_OS,arch:process.env.RUNNER_ARCH,image_os:process.env.ImageOS,image_version:process.env.ImageVersion,node:process.version,powershell_hosted_workflow:true},software:{main:'Playwright',version:'1.62.0',browser:'Chromium',executed:true},attachment_sha256:attachments,task_text_sha256:taskHashes,workbook_checks:{answer_sheet_names:sheets(path.join(artifactRoot,'关键标准答案.xlsx')),specification_sheet_names:['任务规格转化'],task_spec_column_count:2},platform_audit:{platform_specific_members:platform,linux_executables_executed:false,no_wsl_required:true,no_linux_container_required:true,no_posix_shell_required:true,cross_platform_paths:true},clean_runs:cleanRuns,reference_match:true,positive_mutation:{changed_rule:'Japanese shipping caption text',exit_code:0,report_changed:true},invalid_input:{changed_rule:'caption_tracks.json missing',exit_code:r.code,no_delivery_output:true},network:{installation:'npm and Playwright sources',formal_run:'loopback only'}};await fsp.writeFile(path.join(evidenceRoot,'windows-verification.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
